### ISSUE TITLE
Move fprof/cprof/eprof and percept2 into the same section

### ISSUE THREAD

**Issue by aboroska** [unbalancedparentheses/spawnedshelter#26]
They should belong to the same category. Either Debugging or Performance.

Or perhaps to new category called Profiling.

What do you think?

**Comment by unbalancedparentheses** [comment]
You are right

**Comment by unbalancedparentheses** [comment]
Check it out: http://spawnedshelter.com/#profiling

Let me know if there is anything else that can be better done.
