### ISSUE TITLE
Joe Armstrong "My Favorite Erlang Program" URL has changed

### ISSUE THREAD

**Issue by pejrich** [unbalancedparentheses/spawnedshelter#48]
Was `https://joearms.github.io/2013/11/21/My-favorite-erlang-program.html` but now it is `https://joearms.github.io/published/2013-11-21-My-favorite-erlang-program.html`

`src/content.md` line 29 should be changed to `- [My favorite Erlang program - Joe Armstrong](https://joearms.github.io/published/2013-11-21-My-favorite-erlang-program.html)`

**Comment by unbalancedparentheses** [comment]
create a pull request please
