### ISSUE TITLE
Broken link : "10 Essential Erlang Tools for Erlang Developers"

### ISSUE THREAD

**Issue by Laymer** [unbalancedparentheses/spawnedshelter#57]
### [10 Essential Erlang Tools for Erlang Developers](https://github.com/unbalancedparentheses/spawnedshelter/blob/master/src/content.md#advanced-erlang)
The provided link is broken but this one seems to work just fine :

[10 Essential Erlang Tools for Erlang Developers](https://www.pluralsight.com/guides/10-essential-erlang-tools-for-erlang-developers)

Hope this helps,

Best

**Comment by unbalancedparentheses** [comment]
Fixed! Thanks
